package com.cm4j.test.euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * 求满足上述规则 (前2个数相加得第三个数) 《 偶数项 》 之和
 * 
 * @author yang.hao
 * @since 2011-6-21 下午04:34:38
 * 
 */
public class P2 {

	public static void main(String[] args) {
		long start = System.nanoTime();
		int max = 4000000;

		int a = 1;
		int b = 2;
		int c = 0;

		int result = 0;

		while (c < max) {
			if (c % 2 == 0) {
				result += c;
				System.out.println("c:" + c);
			}
			c = a + b;
			a = b;
			b = c;
		}
		long end = System.nanoTime();

		System.out.println(result + 2);
		System.out.println("take:" + (end - start));
	}
}
